import type { VersionedRecord, VersionRef } from "@/lib/versioning/types";
import { generateCanonicalId } from "@/lib/versioning/id";

/**
 * PRIORITY B6 — the versioned Simulation Scenario model. A scenario names
 * EVERY input the deterministic engine (simulation/engine.ts, Priority B7)
 * needs to reproduce an identical result: same seed + same scenario version
 * + same simulator version => same output, always (see
 * simulation/engine.ts's own doc comment and
 * docs/EYEONPIT_1_6_ARCHITECTURE.md's "Reproducibility" section).
 */

export interface BettingStrategyStep {
  /** The true count AT OR ABOVE which this bet applies — steps are evaluated in descending trueCountThreshold order, first match wins. A `trueCountThreshold` of `-Infinity` acts as the base/default bet. */
  trueCountThreshold: number;
  betUnits: number;
}

export interface BettingStrategy extends VersionedRecord {
  name: string;
  /** Sorted descending by trueCountThreshold at validation time — see validateBettingStrategy. */
  steps: BettingStrategyStep[];
  /** True count at/below which the strategy "wongs out" (stops betting/leaves) — omitted if the strategy never leaves. */
  wongOutThreshold?: number;
  /** True count at/above which the strategy "wongs in" (starts betting after sitting out) — omitted if the strategy always plays. */
  wongInThreshold?: number;
}

export type PlayingDeviation = {
  /** Free-text description of the deviation (e.g. "16v10: stand at TC>=0") — Priority B4 explicitly forbids inventing index numbers; deviations here must be user/research-supplied, never generated by this schema. */
  description: string;
  trueCountThreshold: number;
};

export interface PlayingStrategy extends VersionedRecord {
  name: string;
  /** "basic" = zero-deviation basic strategy only. "basic-plus-deviations" = basic strategy plus the deviations listed. Never "count-optimal" or similar — this schema does not claim to know optimal play, only what basic strategy + named deviations produce. */
  baseStrategy: "basic";
  deviations: PlayingDeviation[];
}

export interface SimulationScenario extends VersionedRecord {
  name: string;
  gameDefinitionRef: VersionRef;
  countMethodRef: VersionRef;
  bettingStrategyRef: VersionRef;
  playingStrategyRef: VersionRef;
  /** 0-100, overrides GameDefinition's own penetrationPercent for this scenario if different (e.g. testing sensitivity to penetration) — omitted to use the game definition's own value. */
  penetrationOverridePercent?: number;
  /** Starting bankroll in betting units — used only for risk-of-ruin-style metrics in the result, never to gate the simulation itself. */
  startingBankrollUnits: number;
  handsToSimulate: number;
  /** Explicit integer seed — REQUIRED, never randomly chosen at run time, so the same scenario always reproduces the same result (Priority B6's core requirement). */
  seed: number;
  notes?: string;
}

export type CreateSimulationScenarioInput = Omit<SimulationScenario, keyof VersionedRecord>;

export type ScenarioValidation = { valid: true } | { valid: false; errors: string[] };

export function validateSimulationScenario(input: CreateSimulationScenarioInput): ScenarioValidation {
  const errors: string[] = [];
  if (!input.name.trim()) errors.push("Scenario name is required.");
  if (!Number.isInteger(input.handsToSimulate) || input.handsToSimulate < 1) {
    errors.push("handsToSimulate must be a positive integer.");
  }
  if (!Number.isInteger(input.seed)) errors.push("seed must be an integer.");
  if (input.startingBankrollUnits < 0) errors.push("startingBankrollUnits must be non-negative.");
  if (input.penetrationOverridePercent != null && (input.penetrationOverridePercent <= 0 || input.penetrationOverridePercent > 100)) {
    errors.push("penetrationOverridePercent must be between 0 (exclusive) and 100.");
  }
  return errors.length > 0 ? { valid: false, errors } : { valid: true };
}

export function buildSimulationScenario(input: CreateSimulationScenarioInput): SimulationScenario {
  const validation = validateSimulationScenario(input);
  if (!validation.valid) throw new Error(`Invalid simulation scenario: ${validation.errors.join(" ")}`);
  const now = new Date().toISOString();
  return { ...input, id: generateCanonicalId(), version: 1, createdAt: now, updatedAt: now };
}

export function validateBettingStrategy(steps: BettingStrategyStep[]): boolean {
  return steps.every((s) => s.betUnits > 0) && steps.length > 0;
}

/** Selects the applicable bet for a given true count — first step (in descending-threshold order) whose threshold the true count meets or exceeds. */
export function betUnitsForTrueCount(strategy: BettingStrategy, trueCount: number): number {
  const sorted = [...strategy.steps].sort((a, b) => b.trueCountThreshold - a.trueCountThreshold);
  const match = sorted.find((s) => trueCount >= s.trueCountThreshold);
  return match?.betUnits ?? sorted[sorted.length - 1]?.betUnits ?? 1;
}
