// @vitest-environment jsdom
//
// Hand-verified fixed sequences — every expected number below was computed
// by hand (see the comment above each fixture), not generated by the
// oracle or by production. These are a *supplement* to the existing
// "mandatory acceptance sequence" fixtures in
// src/lib/db/repositories/cardEvents.test.ts, which remain the primary
// hand-verified fixtures and are left untouched — this file adds a couple
// of independent examples of its own rather than replacing anything.
//
// Random simulation (countingValidation.smoke/.standard/.stress) covers
// breadth; these fixed sequences cover a small number of cases a human can
// fully check by re-deriving the arithmetic from docs/counting-systems.md's
// published tag tables without running any code at all.
import { beforeEach, describe, expect, it } from "vitest";
import { calculateCountSnapshot } from "@/lib/counting-engine/calculateCounts";
import { roundTrueCountForDisplay } from "@/lib/counting-engine/calculateTrueCount";
import { addCardToRound, getCardEventsForShoe } from "@/lib/db/repositories/cardEvents";
import { createInvestigation, occupySeat, resetAllData } from "@/lib/db/repositories/investigations";
import type { CardCode, Rank } from "@/types/investigation";

beforeEach(async () => {
  await resetAllData();
});

async function freshInvestigation(shoeTotalDecks: number) {
  return createInvestigation({
    casino: "", tableNumber: "", dealerName: "", investigationDate: "2026-08-09",
    operatorName: "", countingSystem: "Hi-Lo", shoeTotalDecks, status: "active",
  });
}

function dealerAdd(investigationId: string, roundId: string, rank: Rank) {
  return addCardToRound({
    investigationLocalId: investigationId, roundId, targetType: "dealer", targetId: "dealer", rank,
    applyToRound: (r) => ({ ...r, dealerHand: { cards: [...r.dealerHand.cards, { rank, suit: "unspecified" } as CardCode] } }),
    event: { type: "card", message: `Dealer: ${rank}` },
  });
}

function seatAdd(investigationId: string, roundId: string, seatNumber: number, rank: Rank) {
  return addCardToRound({
    investigationLocalId: investigationId, roundId, targetType: "seat", targetId: seatNumber, rank,
    applyToRound: (r) => {
      const seat = r.seats[seatNumber];
      if (!seat) return r;
      return { ...r, seats: { ...r.seats, [seatNumber]: { ...seat, playerCards: [...seat.playerCards, { rank, suit: "unspecified" } as CardCode] } } };
    },
    event: { type: "card", message: `Seat ${seatNumber}: ${rank}` },
  });
}

describe("hand-verified fixture 1: single deck, dealer draws K, A, 5", () => {
  it("matches every system's running/true count computed by hand", async () => {
    const inv = await freshInvestigation(1);
    const round = inv.rounds[0];
    await dealerAdd(inv.localId, round.id, "K");
    await dealerAdd(inv.localId, round.id, "A");
    await dealerAdd(inv.localId, round.id, "5");

    const events = await getCardEventsForShoe(inv.localId, round.shoeNumber);
    const snapshot = calculateCountSnapshot(events, 1);

    // By hand, from docs/counting-systems.md's tag tables:
    //   Hi-Lo:     K=-1, A=-1, 5=+1  -> running = -1
    //   KO:        IRC(1 deck)=0; K=-1, A=-1, 5=+1 -> running = -1
    //   Zen:       K=-2, A=-1, 5=+2  -> running = -1
    //   Omega II:  K=-2, A=0,  5=+2  -> running =  0
    //   exposedCardCount = 3; decksRemaining = (52-3)/52 = 49/52
    //   trueCount(balanced) = running / (49/52) = running * 52/49
    //     Hi-Lo: -1 * 52/49 = -52/49
    //     Zen:   -1 * 52/49 = -52/49
    //     Omega II: 0 * 52/49 = 0
    const decksRemaining = 49 / 52;
    expect(snapshot.exposedCardCount).toBe(3);
    expect(snapshot.decksRemaining).toBeCloseTo(decksRemaining, 12);
    expect(snapshot["Hi-Lo"].running).toBe(-1);
    expect(snapshot["Hi-Lo"].trueCount).toBeCloseTo(-1 * (52 / 49), 12);
    expect(snapshot.KO.running).toBe(-1);
    expect(snapshot.KO.trueCount).toBeNull();
    expect(snapshot.Zen.running).toBe(-1);
    expect(snapshot.Zen.trueCount).toBeCloseTo(-1 * (52 / 49), 12);
    expect(snapshot["Omega II"].running).toBe(0);
    expect(snapshot["Omega II"].trueCount).toBeCloseTo(0, 12);

    // Display rounding, also checked by hand: -52/49 = -1.0612..., rounds to -1.1.
    expect(roundTrueCountForDisplay(snapshot["Hi-Lo"].trueCount)).toBe(-1.1);
  });
});

describe("hand-verified fixture 2: 6-deck shoe, Seat 3 draws four 2s, dealer draws two 10s", () => {
  it("matches every system's running/true count computed by hand, including KO's non-zero IRC", async () => {
    const inv = await freshInvestigation(6);
    await occupySeat(inv.localId, 3);
    const round = inv.rounds[0];
    await seatAdd(inv.localId, round.id, 3, "2");
    await seatAdd(inv.localId, round.id, 3, "2");
    await seatAdd(inv.localId, round.id, 3, "2");
    await seatAdd(inv.localId, round.id, 3, "2");
    await dealerAdd(inv.localId, round.id, "10");
    await dealerAdd(inv.localId, round.id, "10");

    const events = await getCardEventsForShoe(inv.localId, round.shoeNumber);
    const snapshot = calculateCountSnapshot(events, 6);

    // By hand:
    //   Hi-Lo:    4x(2=+1) + 2x(10=-1) = 4 - 2 = +2
    //   KO:       IRC(6 decks) = -4*(6-1) = -20; tags same as Hi-Lo here
    //             (2=+1, 10=-1) -> running = -20 + 4 - 2 = -18
    //   Zen:      4x(2=+1) + 2x(10=-2) = 4 - 4 = 0
    //   Omega II: 4x(2=+1) + 2x(10=-2) = 4 - 4 = 0
    //   exposedCardCount = 6; decksRemaining = (6*52 - 6)/52 = 306/52
    //   trueCount(balanced) = running / (306/52) = running * 52/306
    //     Hi-Lo: 2 * 52/306 = 104/306
    //     Zen, Omega II: 0
    const decksRemaining = 306 / 52;
    expect(snapshot.exposedCardCount).toBe(6);
    expect(snapshot.decksRemaining).toBeCloseTo(decksRemaining, 12);
    expect(snapshot["Hi-Lo"].running).toBe(2);
    expect(snapshot["Hi-Lo"].trueCount).toBeCloseTo(104 / 306, 12);
    expect(snapshot.KO.running).toBe(-18);
    expect(snapshot.KO.trueCount).toBeNull();
    expect(snapshot.Zen.running).toBe(0);
    expect(snapshot.Zen.trueCount).toBeCloseTo(0, 12);
    expect(snapshot["Omega II"].running).toBe(0);
    expect(snapshot["Omega II"].trueCount).toBeCloseTo(0, 12);
  });
});
